# This is a basic workflow to help you get started with Actions

name: Check and notify

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
  - cron: "0 8-12 * * 1-5"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      - uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
        
      - name: Setup coursier
        uses: coursier/cache-action@v6

      - name: Setup ammonite
        uses: coursier/setup-action@v1
        with:
          jvm: adopt:11
          apps: ammonite
          
      - name: launch script
        id: fetch_url
        run: echo "::set-output name=url::$(amm check_url.sc)"
          
      - name: check url
        run: echo ${{steps.fetch_url.outputs.url}}
        
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        if: ${{steps.fetch_url.outputs.url != ''}}
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Nueva versión del sae ${{steps.fetch_url.outputs.url}}
            
      - name: commit updated file for state
        if: ${{steps.fetch_url.outputs.url != ''}}
        run: |
          git add executions.txt
          git commit -m "new version update"
          git push
